@startuml
skinparam classAttributeIconSize 0
hide circle

!theme plain
top to bottom direction
skinparam linetype ortho

class Main {
  + Main(): 
  + main(String[]): void
}
class Matrice {
  + Matrice(int, int, int): 
  + Matrice(int, int[][]): 
  - values: int[][]
  - n: int
  - m: int
  - modulo: int
  + getM(): int
  + getModulo(): int
  + at(int, int): int
  + toString(): String
  + getN(): int
}
class Operator {
  ~ Operator(String):
  - symbole: String
  # op(int, int): int
  + getSymbole(): String
  + operate(Matrice, Matrice): Matrice
}
class Minus {
  + Minus(): 
  # op(int, int): int
}
class Mult {
  + Mult(): 
  # op(int, int): int
}
class Plus {
  + Plus(): 
  # op(int, int): int
}

Main     "1"  -[#595959,dashed]->  "*" Operator : creat >
Main     "1"  -[#595959,dashed]->  "2" Matrice  : possess >

Operator  ^-[#000082,plain]-    Plus
Operator  ^-[#000082,plain]-    Minus
Operator  ^-[#000082,plain]-    Mult

@enduml
